### ISSUE TITLE
Remove old / superfluous code

### ISSUE THREAD

**Issue by mhtess** [mhtess/gen-games#17]
Lots of comments of tangrams and color code.. remove all but the most important `console.log()`

**Comment by ashulman18** [comment]
Determine whether or not we want round number related information. If so, where is it necessary?

**Comment by ashulman18** [comment]
planning to keep this issue open until we launch so I can clean it up more later. the messier stuff is what I commented more on for our sake. However, the mp game file and html file I didn't comment much on because we know how those work - this I'll comment on when we are closer to a finished first round

**Comment by mhtess** [comment]
This issue is too vague to keep open.
